site_name: Homelab Bernardo
site_description: Documentação simples e portefólio do meu Homelab
site_author: Bernardo Silva

theme:
  name: material
  language: pt
  palette:
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Mudar para tema claro
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Mudar para tema escuro
  features:
    - navigation.top
    - search.suggest
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - tables

docs_dir: docs

nav:
  - Início: index.md
  - Infraestrutura: infraestrutura.md
  - Serviços: servicos.md
  - Projetos: projetos.md
  - Sobre: sobre.md
